### ISSUE TITLE
soru

### ISSUE THREAD

**Issue by witchfindertr** [eneskaya96/fortune_telling#1]
SocialShare.shareInstagramStory(
      appId: "888268445701700",
      imagePath: path,
      backgroundTopColor: "#F9F9FA",
      backgroundBottomColor: "#F9F9FA",
    ).then((data) {
      print("cccccllll");
      print(data);
    }
    );
  }

reis instagramda paylaşırken appid vermek zorundamıyızz ?

**Comment by eneskaya96** [comment]
Yes, it should have app id according to new version of social share
